version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 80:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
        - mysql-db
  mysql-admin:
    depends_on:
    - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: mysql-admin
    restart: always
    ports:
    - '7000:80'
    environment:
      PMA_HOST: mysql-db
    networks:
      backend:
        aliases:
           - mysql-admin

  redis-app:
    image: redis:4.0
    container_name: redis-app
    ports:
        - "6379:6379"
    networks:
      backend:
        aliases:
           - redis-app

networks:
  backend:
    name: backend-network